language: node_js
node_js:
  - '7'
dist: trusty

script:
  - npm install
  - npm run build
  - npm prune --production
  - docker build -t holmescode/web:latest -t holmescode/web:$TRAVIS_BUILD_NUMBER .

after_success:
 - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
 - docker push holmescode/web:$TRAVIS_BUILD_NUMBER
 - docker push holmescode/web:latest
