language: csharp
solution: ./src/holmescode.com.csproj
mono: none
dotnet: 1.0.4
dist: trusty

script:
  - cd src && npm install && cd ..
  - npm install gulp -g
  - dotnet restore $TRAVIS_BUILD_DIR/src/holmescode.com.csproj
  - dotnet publish $TRAVIS_BUILD_DIR/src/holmescode.com.csproj -c Release -o $TRAVIS_BUILD_DIR/dist
  - ls $TRAVIS_BUILD_DIR/dist
  - docker build -t holmescode/web:latest -t holmescode/web:$TRAVIS_BUILD_NUMBER .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push holmescode/web:$TRAVIS_BUILD_NUMBER
  - docker push holmescode/web:latest
